# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/ReportingServiceWebJob.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/ReportingServiceWebJob.csproj'
    arguments: '--output $(System.DefaultWorkingDirectory)/publish_output/app_data/Jobs/Triggered/ReportingServiceWebJob'
    zipAfterPublish: false
    modifyOutputPath: false
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
  artifact: drop
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Professional Subscription (c34b492b-56d1-4226-95d1-426b7e63f2c7)'
    appType: 'webApp'
    WebAppName: 'WebJobsApp20220331042226'
    packageForLinux: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'